### ISSUE TITLE
Noah: Duplicate code could be turned into a function

### ISSUE THREAD

**Issue by juliebarwick** [QNK-Industries/Loungeo#68]
https://github.com/QNK-Industries/Loungeo/blob/4709ccf09a861902a2c9580513952bb29d4f0d08/client/src/Overview/components/ExpandedView.jsx#L39-L42

Consider making this code one function that calculates the values needed to avoid duplicating logic.

Also in this file:
For places that have event handlers such as this:
`onMouseLeave={() => { setImageClick(!imageClick); }}`
You can omit the {} on the function:
`onMouseLeave={() => setImageClick(!imageClick)}`

**Comment by xanzadu** [comment]
Helpered.
