### ISSUE TITLE
Noah: suggest to stick with styled components instead of using inline styles

### ISSUE THREAD

**Issue by juliebarwick** [QNK-Industries/Loungeo#69]
https://github.com/QNK-Industries/Loungeo/blob/4709ccf09a861902a2c9580513952bb29d4f0d08/client/src/Overview/components/ZoomedView.jsx#L38

I believe you could make this logic work in styled-components as well since styled-components lets you take advantage of props.

**Comment by xanzadu** [comment]
Fixed.
