### ISSUE TITLE
Quinton: simplify event handler

### ISSUE THREAD

**Issue by juliebarwick** [QNK-Industries/Loungeo#72]
https://github.com/QNK-Industries/Loungeo/blob/4709ccf09a861902a2c9580513952bb29d4f0d08/client/src/Ratings_Reviews/components/ReviewSearch.jsx#L15

This line could simply be written as:
`onChange={searchFilter}`
(event is automatically passed as first argument)

**Comment by maki-q** [comment]
Fixed!
